services:
  rms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rms_service
    restart: on-failure
    env_file:
      - ./.env
    # Не монтируем node_modules и даже не монтируем код в проде:
    # volumes:
    #   - ./:/app
    #   # - /app/node_modules
    working_dir: /app
    command: npm start
