// src/loader/tableCreator.js
import { clickhouseReplicaClient, getMongoClient } from '../config/config.js';
import { createClient } from '@clickhouse/client';
import { tablesConfig } from '../config/tables.js';
import { logInfo, logError } from '../utils/logging.js';

/**
 * Создаёт ClickHouse–клиент к исходной базе
 */
function getSourceClient(host, secure, user, pass) {
  const protocol = secure === 'true' ? 'https' : 'http';
  const url = `${protocol}://${host}`;
  return createClient({ url, username: user, password: pass });
}

export async function createTables() {
  for (const tbl of tablesConfig) {
    if (!tbl.enabled) {
      logInfo(`🛑 Skipping '${tbl.name}' (disabled)`);
      continue;
    }

    let ddl;  // убрали аннотацию типа

    if (tbl.source === 'mongo') {
      // ... здесь ваш код автогенерации DDL по Mongo (как раньше) ...
    }
    else { // tbl.source === 'clickhouse'
      if (tbl.autoGenerateDDL) {
        // 1) подключаемся к продовой ClickHouse
        const srcClient = getSourceClient(
          tbl.sourceDatabase,
          process.env.REPLICA_CH_SECURE,
          process.env.LIVEDIGITAL_CH_USER,
          process.env.LIVEDIGITAL_CH_PASSWORD
        );

        // 2) вытягиваем метаданные колонок
        const query = `
          SELECT name, type
            FROM system.columns
           WHERE database = '${tbl.sourceSchema}'
             AND table = '${tbl.sourceTable}'
           ORDER BY position
        `;
        const result = await srcClient.query({ query, format: 'JSON' });
        const { data } = await result.json();

        // 3) строим список столбцов
        const cols = data.map(col => `  ${col.name} ${col.type}`).join(',\n');

        // 4) генерим DDL в целевой схеме
        const baseName = `${tbl.prefix ? tbl.prefix + '_' : ''}${tbl.sourceTable}`;
        const qualified = `${tbl.targetSchema}.${baseName}`;
        ddl = 
          `CREATE TABLE IF NOT EXISTS ${qualified} (\n` +
          cols + '\n)' +
          ` ENGINE = MergeTree\n` +
          `PARTITION BY toYYYYMM(timestamp)\n` +
          `ORDER BY (toDate(timestamp), ${data[0].name})`;  // делаем ORDER BY по первой колонке

        await srcClient.close();
      }
      else {
        // используем статичный ddl из config/tables.js
        const prefix = process.env.TABLE_PREFIX || '';
        const base = `${prefix}_${tbl.sourceTable}`;
        const qualified = `${tbl.targetSchema}.${base}`;
        ddl = tbl.ddl.replace(
          /CREATE TABLE IF NOT EXISTS \${prefix}_\${sourceTable}/,
          `CREATE TABLE IF NOT EXISTS ${qualified}`
        );
      }
    }

    // запускаем DDL в реплике
    logInfo(`🔨 Creating table '${tbl.name}'`);
    try {
      await clickhouseReplicaClient.query({ query: ddl });
      logInfo(`✅ Table '${tbl.name}' ready`);
    } catch (err) {
      logError(`Failed to create '${tbl.name}'`, err);
      throw err;
    }
  }
}
