/**
 * Список таблиц/коллекций для создания в ClickHouse-реплике.
 * Каждому item можно задать:
 *   - enabled: величина, включена ли подгрузка/DDL
 *   - source: 'mongo' или 'clickhouse'
 *   - для clickhouse: sourceDatabase, sourceSchema, sourceTable, ddl
 *   - для mongo: sourceSchema (имя БД в Mongo), sourceTable (коллекция)
 *   - targetSchema: имя схемы в ClickHouse-реплике
 */

import 'dotenv/config';
export const tablesConfig = [
  {
    name: 'calls',
    source: 'mongo',
    sourceSchema: 'moodhood',
    sourceTable: 'calls',
    enabled: true,
    targetSchema: process.env.REPLICA_SCHEMA,
    autoGenerateDDL: true,  // генерировать DDL по sample-документу
  },
  {
    name: 'time_spent',
    source: 'clickhouse',
    sourceDatabase: process.env.LIVEDIGITAL_CH_HOST,
    sourceSchema: 'analytics_prod',
    sourceTable: 'time_spent',
    prefix: process.env.TABLE_PREFIX || '',
    targetSchema: process.env.REPLICA_SCHEMA,
    enabled: true,
    autoGenerateDDL: true,
  },
  {
    name: 'network_metrics',
    source: 'clickhouse',
    sourceDatabase: process.env.LIVEDIGITAL_CH_HOST,
    sourceSchema: 'analytics_prod',
    sourceTable: 'network_metrics',
    prefix: process.env.TABLE_PREFIX || '',
    targetSchema: process.env.REPLICA_SCHEMA,
    enabled: true,
    autoGenerateDDL: true,
  },
  {
    name: 'metrics',
    source: 'clickhouse',
    sourceDatabase: process.env.LIVEDIGITAL_CH_HOST,
    sourceSchema: 'analytics_prod',
    sourceTable: 'metrics',
    prefix: process.env.TABLE_PREFIX || '',
    targetSchema: process.env.REPLICA_SCHEMA,
    enabled: true,
    autoGenerateDDL: true,
  },
  {
    name: 'feedbacks',
    source: 'clickhouse',
    sourceDatabase: process.env.LIVEDIGITAL_CH_HOST,
    sourceSchema: 'analytics_prod',
    sourceTable: 'feedbacks',
    prefix: process.env.TABLE_PREFIX || '',
    targetSchema: process.env.REPLICA_SCHEMA,
    enabled: true,
    autoGenerateDDL: true,
  }
];
